TARGETNAME := $(APP)
CONFIG_FLASH := 1
CONFIG_GPIO := 1
CONFIG_UART := 1
CFLAGS += -DCONFIG_UART_STM32_RX_INTERRUPT
CONFIG_MINIO := 1
CONFIG_CLI := 1
CONFIG_SPI_SW := 1
CFLAGS += -DCONFIG_SPI_SW_BUSES=2
CONFIG_NVMTNV := 1
CONFIG_TICK_TIMER := 1
CFLAGS += -DCONFIG_TICK_TIMER_STM32_HW_TIM=4 -DCONFIG_TICK_TIMER_STM32_PRESCALER=1099
CONFIG_CRYSTAL_TEST := 1
CONFIG_RINGBUFFER := 1

CFILES += $(wildcard apps/$(APP)/*.c)
CFILES += $(wildcard apps/$(APP)/ui/*.c)
CFILES += apps/$(APP)/fonts/fonts.c
INCLUDE += apps/$(APP)
CFLAGS += -DHAL_NOR_MODULE_ENABLED
LDFLAGS_LATE += --script=apps/$(APP)/kiln.ld
