TARGETNAME := $(APP)
CONFIG_FLASH := 1
CONFIG_GPIO := 1
CONFIG_UART := 1
CONFIG_MINIO := 1
CONFIG_CLI := 1
CONFIG_CRYSTAL_TEST := 1
CONFIG_NRF52_TEST_BLE_DTM := 1
CONFIG_NRF52_TEST_RADIO := 1

CFILES += $(wildcard source/$(APP)/*.c)
