TARGETNAME := $(APP)
CONFIG_FLASH := 1
CONFIG_GPIO := 1
CONFIG_UART := 1
CFLAGS += -DCONFIG_UART_STM32_RX_INTERRUPT
CONFIG_MINIO := 1
CONFIG_CLI := 1
CONFIG_SPI_SW := 1
CFLAGS += -DCONFIG_SPI_SW_BUSES=1
CONFIG_NVMTNV := 1
CONFIG_TICK_TIMER := 1
CFLAGS += -DCONFIG_TICK_TIMER_STM32_HW_TIM=3 -DCONFIG_TICK_TIMER_STM32_PRESCALER=1099
CONFIG_RINGBUFFER := 1

CFLAGS_LATE += -Wno-inline -Wno-cast-align

CFILES += $(wildcard apps/$(APP)/*.c)
CFILES += $(wildcard apps/$(APP)/fonts/*.c)
INCLUDE += apps/$(APP)
INCLUDE += apps/$(APP)/fonts
LDFLAGS_LATE += --script=apps/$(APP)/minikiln.ld
